### PR TITLE
Add August meeting

### PR DESCRIPTION
**Pull request by travi**
closes dsmjs/talk-proposals#52

### CODE REVIEW

**Comment by travi** [comment]
getting this together later than i was hoping, but trying to get as much together as i can while i have a little time. a few questions before merging this though:

@michaelwclark 
* was downtown gravitate confirmed as the hosting location?
* do i have the links correct for tek and limelight?

@PaulSearcy
* the summary I had to work with from dsmjs/talk-proposals#52 was a little thin on detail. do you have any additional information that you think would be worth us sharing on the website?

**Comment by travi** [comment]
i still need to get eventbrite added but will try to get that added soon as well

**Comment by travi** [comment]
merged what we know. we can update if anything needs adjustment. i'll try to get a tweet out tomorrow

**Comment by PaulSearcy** [comment]
I’m here! 

@michaelwclark  has been texting me with updates so I didn’t see this right away.

For details on the talk.

It’s mainly about a specific application I used it to generate a PDF of a webpage in print format and download it for the user automatically. In that the user doesn’t have to hit the print button, select save, and then specify a save location.

In addition to that I’ve done research on to other related  applications or tools. Such as usage with Selenium and in Jasmine. I’ll also touch on lighthouse the auditing tool in chrome that can be run headless now also.

The talk is going to be focused at first then broad since there is a lot of uses for it.

**Pull request merged**
