### PR TITLE
Janurary: Intermediate debugging by example

### PR DESCRIPTION
**Pull request by toranb**
@travi @crolek I've included details for my January 9th talk on `intermediate debugging`

Any questions or concerns let me know - I left Gain in the location spot but you could easily alter this when you know more about the meeting location & sponsor.

### CODE REVIEW

**Comment by crolek** [comment]
👍

**Comment by travi** [comment]
If we want to include a message on the website about there not being a meeting in December, we need to include it as part of this, correct @crolek?  Chuck, if you could add a message here, i can get a reminder tweet out in the morning

**Comment by crolek** [comment]
Yup. December "no meeting" notification has been pushed.

**Comment by toranb** [comment]
@crolek @travi could we get this up Sunday/Monday? A week from Tue the 2nd will come up quick ;)

**Pull request merged**
