### PR TITLE
Add presentation details for July

### PR DESCRIPTION
**Pull request by travi**

### CODE REVIEW

**Comment by toranb** [comment]
hmm so what happ to my PR boss? I've had it up /pending a look (included all the same source allies stuff I see here)

**Comment by travi** [comment]
haha, good question. i guess i didnt realize that one was out there. mine broke things anyway, so i'll work on getting them merged

**Comment by travi** [comment]
@toranb i had to change the `:` in your title to a `-` so that the front matter would parse correctly. if you'd rather it be something else, let us know

**Comment by toranb** [comment]
@travi not to worry boss :) glad to have this [website](https://dsmjs.com/) updated and 2 talks listed! See you next week!

**Pull request merged**
