### PR TITLE
Jan2019 talk

### PR DESCRIPTION
**Pull request by michaelwclark**
Added meeting and talk info for Jan 2019 meeting. 

Presenter: @churchs19 
Host: Source Allies.

Todo: Verify eventbrite. https://www.eventbrite.com/preview?eid=54298495261

### CODE REVIEW

**Comment by travi** [comment]
@churchs19 the details we have are live on https://dsmjs.com/. please let us know if there are any details that you would like us to update before we start to market further.

**Comment by churchs19** [comment]
@travi, I think I'd update the description to something like the following:

"I've been playing with the Lego Boost robotics platform lately to build a remote control for the Boost Move Hub using Angular 7, TypeScript, and Node.js. The Boost Move Hub communicates with an app or the PC through a Bluetooth Low Energy connection. I thought the community would enjoy learning about what I’ve learned in the process and some of the potential for automated Lego creations."

I've tweaked my remote control and the build to be more focused on the robot than the vehicle at this point for the purpose of the presentation since it better shows off the potential of the platform and since Lego has since released additional hubs and accessories since I made the original proposal.

**Comment by churchs19** [comment]
@travi I'll also send you a GitHub link for the presentation slides that you can add when I get those up in the next day or so.

**Comment by michaelwclark** [comment]
@churchs19 @travi I've made the updates to the talk description. @churchs19  just tag myself or @travi when you have a link to the slides and we will get the site updated when you are ready.

Thanks!

**Comment by travi** [comment]
updated. thanks! looking forward to the talk

**Pull request merged**
